pluginManagement {
	repositories {
		// NES fork: 内网 Nexus 私服优先（引用 ~/.gradle/gradle.properties 中的全局属性），加速插件下载
		maven {
			name = 'nexus'
			url = nexusPublicUrl
			allowInsecureProtocol = true
			credentials {
				username = nexusUsername
				password = nexusPassword
			}
		}
		gradlePluginPortal()
		mavenCentral()
	}
}

plugins {
	id 'io.spring.develocity.conventions' version '0.0.25'
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'spring-kafka-dist'

include 'spring-kafka'
include 'spring-kafka-bom'
include 'spring-kafka-test'
include 'spring-kafka-docs'
